# The bitergia elasticsearch + kibiter "secured" images use the
# SecureGuard plugin with its demo user credentials and certificates.
# See https://docs.search-guard.com/latest/installation-windows

mordred:
  # This version was recommended in CHAOSS slack as it works with
  # AWS's open source version of Elasticsearch
  image: bitergia/mordred:grimoirelab-0.2.57
  volumes:
    - ./conf/setup.cfg:${MORDRED_CONF}/setup.cfg
    - ./conf/credentials.cfg:${MORDRED_CONF}/credentials.cfg
    - ../orgs.json:${MORDRED_CONF}/orgs.json
    - ./conf/simple-projects.json:${MORDRED_CONF}/simple-projects.json
    - ./conf/aliases.json:${MORDRED_CONF}/aliases.json
    - ./logs:${MORDRED_CONF}/logs
  environment:
    - MORDRED_CONF_FILES=${MORDRED_CONF}/setup.cfg ${MORDRED_CONF}/credentials.cfg
  links:
    - mariadb
    - elasticsearch
    - kibiter

hatstall:
  image: grimoirelab/hatstall:latest
  environment:
    - DATABASE_DIR=/db/
    - ADMIN_USER=${HATSTALL_USER}
    - ADMIN_PASS=${HATSTALL_PASSWORD}
  ports:
    - ${HATSTALL_PORT}:80
  links:
    - mariadb
  volumes:
    -  ./conf/apache-hatstall.conf:/home/grimoirelab/apache-hatstall.conf
    -  ./conf/credentials.cfg:/home/grimoirelab/shdb.cfg

mariadb:
  restart: "always"
  image: mariadb:10.0
  expose:
    - "${MYSQL_PORT}"
  ports:
    - "${MYSQL_PORT}:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_ALLOW_EMPTY_PASSWORD=no

elasticsearch:
  restart: on-failure:5
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6
  environment:
    - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    - network.bind_host=0.0.0.0
    - http.max_content_length=2000mb
    - ANONYMOUS_USER=true
  volumes:
    - ./es-data:/var/lib/elasticsearch
  ports:
    - "${ELASTIC_PORT}:9200"

kibiter:
  restart: on-failure:5
  # See https://github.com/chaoss/grimoirelab-kibiter/releases
  image: bitergia/kibiter:community-v6.8.6-3
  environment:
    - PROJECT_NAME=Kibiter
    - NODE_OPTIONS=--max-old-space-size=1000
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "${KIBANA_PORT}:5601"
