# The bitergia elasticsearch + kibiter "secured" images use the
# SecureGuard plugin with its demo user credentials and certificates.
# See https://docs.search-guard.com/latest/installation-windows

mordred:
  # This version was recommended in CHAOSS slack as it works with
  # AWS's open source version of Elasticsearch
  image: bitergia/mordred:grimoirelab-0.2.57
  volumes:
    - ./conf/setup.cfg:${MORDRED_CONF}/setup.cfg
    - ./conf/credentials.cfg:${MORDRED_CONF}/credentials.cfg
    - ../orgs.json:${MORDRED_CONF}/orgs.json
    - ./conf/simple-projects.json:${MORDRED_CONF}/simple-projects.json
    - ./conf/aliases.json:${MORDRED_CONF}/aliases.json
    - ./logs:${MORDRED_CONF}/logs
  environment:
    - MORDRED_CONF_FILES=${MORDRED_CONF}/setup.cfg ${MORDRED_CONF}/credentials.cfg
  links:
    - mariadb
    - elasticsearch
    - kibiter

hatstall:
  image: grimoirelab/hatstall:latest
  environment:
    - DATABASE_DIR=/db/
    - ADMIN_USER=${HATSTALL_USER}
    - ADMIN_PASS=${HATSTALL_PASSWORD}
  ports:
    - ${HATSTALL_PORT}:80
  links:
    - mariadb
  volumes:
    -  ./conf/apache-hatstall.conf:/home/grimoirelab/apache-hatstall.conf
    -  ./conf/credentials.cfg:/home/grimoirelab/shdb.cfg

mariadb:
  restart: "always"
  image: mariadb:10.0
  expose:
    - "${MYSQL_PORT}"
  ports:
    - "${MYSQL_PORT}:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_ALLOW_EMPTY_PASSWORD=no

elasticsearch:
  restart: on-failure:5
  image: bitergia/elasticsearch:6.8.6-secured
  environment:
    - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    - network.bind_host=0.0.0.0
    - http.max_content_length=2000mb
  volumes:
    - ./es-data:/var/lib/elasticsearch
    - ./conf/sg_internal_users.yml:/elasticsearch/plugins/search-guard-6/sgconfig/sg_internal_users.yml
  ports:
    - "${ELASTIC_PORT}:9200"
  expose:
    - "${ELASTIC_PORT}"

kibiter:
  restart: on-failure:5
  # See https://github.com/chaoss/grimoirelab-kibiter/releases
  image: bitergia/kibiter:secured-v6.8.6-3
  environment:
    - ANONYMOUS_USER=false
    - PROJECT_NAME=Kibiter
    - NODE_OPTIONS=--max-old-space-size=1000
    - ELASTICSEARCH_URL=https://elasticsearch:9200
    - ELASTICSEARCH_USER=${KIBANA_SERVER_USER}
    - ELASTICSEARCH_PASSWORD=${KIBANA_SERVER_PASSWORD}
    - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    - ELASTICSEARCH.REQUESTHEADERSWHITELIST='["Authorization", "sgtenant"]'
    - XPACK_SECURITY_ENABLED=false
  links:
    - elasticsearch
  ports:
    - "${KIBANA_PORT}:5601"
